---
# core: config->messageQueue
messageQueue:
  host: mq.example.com
  port: 5673
# core: config->messageQueue
# core: config->mySetting-defaultSetting
mySetting: ${DW_MY_SETTING}
defaultSetting: ${DW_DEFAULT_SETTING:-default value}
# core: config->mySetting-defaultSetting
server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
