#example: config#messageQueue
messageQueue:
  host: mq.example.com
  port: 5673
#example: config#messageQueue
#example: config#stringSubstitutor
mySetting: ${DW_MY_SETTING}
defaultSetting: ${DW_DEFAULT_SETTING:-default value}
#example: config#stringSubstitutor
server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
