package io.dropwizard.core.server;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.dropwizard.validation.ValidationMethod;
import org.jspecify.annotations.Nullable;

import java.util.Optional;

/**
 * Configuration options for Content Security Policy (CSP).
 *
 * <p>When a {@code policy} or {@code reportOnlyPolicy} is configured, it must contain the
 * {@code $NONCE} placeholder so that the per-request nonce generated by {@link
 * io.dropwizard.jersey.filter.CspFilter} is injected into the header. Omitting {@code $NONCE}
 * means nonces are generated and embedded in templates but the CSP header contains no matching
 * {@code nonce-<value>} directive, silently defeating the protection.
 */
public class CspConfiguration {

    @Nullable
    private String policy;

    @Nullable
    private String reportOnlyPolicy;

    @JsonProperty
    public Optional<String> getPolicy() {
        return Optional.ofNullable(policy);
    }

    @JsonProperty
    public void setPolicy(String policy) {
        this.policy = policy;
    }

    @JsonProperty
    public Optional<String> getReportOnlyPolicy() {
        return Optional.ofNullable(reportOnlyPolicy);
    }

    @JsonProperty
    public void setReportOnlyPolicy(String reportOnlyPolicy) {
        this.reportOnlyPolicy = reportOnlyPolicy;
    }

    /**
     * Validates that the enforcing CSP policy contains the {@code $NONCE} placeholder.
     *
     * <p>A policy without {@code $NONCE} means the generated nonce is never reflected in the
     * {@code Content-Security-Policy} header, silently breaking nonce-based script protection.
     */
    @JsonIgnore
    @ValidationMethod(message = "CSP policy must contain the '$NONCE' placeholder when configured")
    public boolean isPolicyContainingNonce() {
        return policy == null || policy.contains("$NONCE");
    }

    /**
     * Validates that the report-only CSP policy contains the {@code $NONCE} placeholder.
     *
     * <p>A report-only policy without {@code $NONCE} means nonce violations are never reported,
     * silently undermining the ability to detect inline-script attacks during rollout.
     */
    @JsonIgnore
    @ValidationMethod(message = "CSP report-only policy must contain the '$NONCE' placeholder when configured")
    public boolean isReportOnlyPolicyContainingNonce() {
        return reportOnlyPolicy == null || reportOnlyPolicy.contains("$NONCE");
    }
}
