engines:
  pmd:
    enabled: true
  checkstyle:
    enabled: true

ratings:
  paths:
  - "**.java"

exclude_paths:
- "dropwizard-archetypes/"
- "**.png"
- "**.ts"
- "**.p12"
- "**.jts"
- "**.jks"
- "**.keystore"
