engines:
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    config: checkstyle.xml
    channel: "beta"

ratings:
  paths:
  - "**.java"

exclude_paths:
- dropwizard-archetypes/
- docs/
