---
# yamllint disable rule:comments rule:line-length
name: Announce Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag of the release
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven
          server-id: ossrh
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: Project version
        id: project-version
        env:
          CURRENT_TAG: ${{ inputs.tag }}
        run: |
          VERSION=$(./mvnw help:evaluate -q -B -ntp -Dexpression=project.version -DforceStdout=true)
          PREV_TAG=$(git tag | sort --version-sort | grep -B1 "${CURRENT_TAG}" | head -n1)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "current_tag=${CURRENT_TAG}" >> "$GITHUB_OUTPUT"
          echo "previous_tag=${PREV_TAG}" >> "$GITHUB_OUTPUT"
          echo "ref_name=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
      - name: JReleaser
        id: jreleaser
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.project-version.outputs.version }}
          JRELEASER_BRANCH: ${{ steps.project-version.outputs.ref_name }}
          JRELEASER_TAG_NAME: ${{ steps.project-version.outputs.current_tag }}
          JRELEASER_PREVIOUS_TAG_NAME: ${{ steps.project-version.outputs.previous_tag }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GITHUB_USERNAME: ${{ github.actor }}
          JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          JRELEASER_MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          JRELEASER_BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          JRELEASER_BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      - name: JReleaser release output
        if: ${{ always() && steps.jreleaser.conclusion != 'skipped' }}
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
