---
# yamllint disable rule:comments rule:line-length
name: Assign Milestone
# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: 'dropwizard/dropwizard'
          ref: ${{ github.base_ref }}
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - run: |
          milestone=$(./mvnw -ntp -B -fae -q org.apache.maven.plugins:maven-help-plugin:3.4.0:evaluate -Dexpression=project.version -DforceStdout | sed -e 's/-SNAPSHOT//')
          gh pr edit "${PR_NUMBER}" --milestone "${milestone}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
