---
# yamllint disable rule:comments rule:line-length
name: Assign Milestone
# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'dropwizard/dropwizard'
          ref: ${{ github.base_ref }}
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - run: |
          milestone=$(./mvnw -ntp -B -fae -q org.apache.maven.plugins:maven-help-plugin:3.4.0:evaluate -Dexpression=project.version -DforceStdout | sed -e 's/-SNAPSHOT//')
          gh pr edit "${PR_NUMBER}" --milestone "${milestone}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
