name: "Pull Request Docs Check"
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
    - uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2 # tag=0.4
      with:
        docs-folder: "docs/"
