name: "Pull Request Docs Check"
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2 # tag=0.4
      with:
        docs-folder: "docs/"
