name: "Pull Request Docs Check"
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.1
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "docs/"
