---
# yamllint disable rule:comments
name: Pull Request Docs Check
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      # yamllint disable-line rule:line-length
      - uses: ammaraskar/sphinx-action@54e52bfb642e9b60ea5b6bcb05fe3f74b40d290a # 8.2.3
        with:
          docs-folder: docs/
