---
# yamllint disable rule:comments rule:line-length
name: Java CI
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
jobs:
  yamllint:
    name: "\U0001F9F9 yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: 🧹 Run yamllint
        uses: frenck/action-yamllint@34b4bbcaeabedcfefad6adea8c5bbc42af0e2d47 # v1.5.0
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      contents: read
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        java_version:
          - "17"
          - "21"
          - "25"
        os:
          - ubuntu-latest
          - windows-latest
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
      - name: Cache SonarCloud packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        if: ${{ env.SONAR_TOKEN != null && env.SONAR_TOKEN != '' && matrix.java_version == '17'  && matrix.os == 'ubuntu-latest' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build
        run: ./mvnw --no-transfer-progress -V -B -fae -s .github/settings.xml -e "-DtrimStackTrace=false" "-Dsurefire.rerunFailingTestsCount=1" install
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-reports-${{ matrix.os }}-java${{ matrix.java_version }}
          path: '**/*-reports'
      - name: Publish Test Results
        if: github.event.pull_request.head.repo.full_name == 'dropwizard/dropwizard'
        uses: scacap/action-surefire-report@3dacff26879cd2a7f2160d101254032a3707fe6f # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Report (${{ matrix.os }} - Java ${{ matrix.java_version }})
          report_paths: '**/*-reports/TEST-*.xml'
      - name: Analyze with SonarCloud
        if: ${{ env.SONAR_TOKEN != null && env.SONAR_TOKEN != '' && matrix.java_version == '17' && matrix.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw --no-transfer-progress -V -B -ff -s .github/settings.xml "-Dsonar.projectKey=dropwizard_dropwizard" "-Dsonar.organization=dropwizard" "-Dsonar.host.url=https://sonarcloud.io" org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
